version: '3'
services:
  mysql:
    image: mysql:5.7.34
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: codecamp
      TZ: Asia/Tokyo

volumes:
  mysqldata:
    driver: local
